title: Team9 Healthcare Workforce Visuals
description: Power BI Dashboard for Healthcare Employability Insights
theme: minima

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: "markdown"
    values:
      layout: default

include:
  - custom.css
